stages:
  data_injection:
    cmd: python src/data/data_injection.py
    deps:
    - src/data/data_injection.py
    params:
    - data_injection.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/processed

  feature_engineering:
    cmd: python ./src/features/feature_engineering.py
    deps:
    - data/processed
    - src/features/feature_engineering.py
    outs:
    - data/features

  train_model:
    cmd: python ./src/models/train_model.py
    deps:
    - data/features
    - src/models/train_model.py
    outs:
    - models/trained_model.pkl

  predict_model:
    cmd: python ./src/models/predict_model.py
    deps:
    - ./data/features/feature_test.csv
    - ./models/trained_model.pkl
    - ./src/models/predict_model.py
    outs:
    - ./data/predictions/predicted_results.csv
